version: '3'

# BD postgres
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - services
    environment:
      POSTGRES_DB: proveedores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  # Servicios de Proveedores Alpes
  proveedores:
    container_name: proveedores
    hostname: proveedores
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=proveedores
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy

networks:
  services: