networks:
  pulsar:
    driver: bridge

services:

  # Pulsar stand oalone
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    restart: on-failure
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m"
    command: ["bin/pulsar", "standalone"]
    networks:
      - pulsar
  
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - pulsar
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  # Servicios de Proveedores Alpes
  imagenes_medicas:
    container_name: imagenes_medicas
    hostname: imagenes_medicas
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BROKER_HOST=pulsar
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5001:5001"
    networks:
      - pulsar
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_completed_successfully
